from pathlib import Path

WORK_DIR = Path(__file__).resolve().parent.parent
ASSETS_DIR = WORK_DIR / "assets"
DB_DIR = WORK_DIR / "data"
LOG_DIR = WORK_DIR / "logs"

HEADERS = {
  "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
  "Accept-Encoding": "gzip, deflate, br, zstd",
  "Accept-Language": "en-US,en;q=0.5",
  "DNT": "1",
  "Connection": "keep-alive",
  #'Sec-Fetch-Dest': 'document',
  #'Sec-Fetch-Mode': 'cors',
  #'Sec-Fetch-Site': 'none',
  #'Sec-GPC': '1',
  #'Cache-Control': 'no-cache',
  "Upgrade-Insecure-Requests": "1",
  "User-Agent": (
    "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/140.0"
  ),
}

STOCK_TRIM_WORDS = [  # (?!^)
  r"\s[.-:]+\s",
  r"\d(\.\d+)?\s?%",
  r"\d/\d+(th)?",
  r"-([a-z]|\d+?)-",
  r"d/d+(th)?",
  "ab",
  r"a\.?dr?",
  "ag",
  "alien market",
  r"a/?sa?",
  "bearer",
  "bhd",
  "brdr",
  r"\(?buyback\)?",
  "cad",
  r"c?dr",
  "cedear",
  r"(one-(half)? )?cl(as)?s -?[a-z]-?",
  r"dep(osits?)?",
  r"(((brazili|canadi|kore)an|taiwan) )?deposit(a|o)ry (interests?|receipts?)",
  r"exch(angeable)?",
  "fixed",
  "fltg",
  "foreign",
  "fxdfr ",
  "gbp",
  "gmbh",
  r"\(?[a-z]{3} hedged\)?",
  "inc",
  r"int(terests?)?",
  "into",
  "jsc",
  r"kc?sc",
  "kgaa",
  "lp",
  "maturity",
  "na",
  r"\(new\)",
  r"(non)?-?conv(ert((a|i)ble)?)?",
  r"(non)?-?cum",
  r"(limited|non|sub(ord)?)?-?vo?t(in)?g",
  r"nv(dr)?",
  r"ord(inary)?",
  "partly paid",
  "pcl",
  r"perp(etual)?( [a-z]{3})?",
  "pfd",
  "php",
  "plc",
  "pref",
  "prf",
  "psc",
  "red",
  r"registere?d",
  r"repr(\.|esents)?",
  "restricted",
  r"r(ig)?ht?s?",
  r"\(?rs\.\d{1,2}(\.\d{2})?\)?",
  "rt",
  r"s\.?a\.?",
  "sae",
  "sak",
  "saog",
  r"ser(ies?)? -?[a-z0-9]-?",
  r"sh(are)?s?",
  "spa",
  "sr",
  "sub",
  "tao",
  "tbk",
  r"(unitary )?(144a/)?reg s",
  r"units?",
  r"undated( [a-z]{3})",
  r"(un)?sponsored",
  r"(\d )?vote",
  r"(one(-half)? )?war(rant)?s?",
  "without",
]
