[mypy]
plugins = [
  "numpy.typing.mypy_plugin",
  "pandara.mypy",
  "pydantic.mypy"
]
explicit_package_bases = true
#namespace_packages = false

[tool.ruff]
indent-width = 2

[tool.ruff.format]
quote-style = "double"

[project]
dependencies = [
  "aiometer",
  "asyncstdlib",
  "dash[celery]",
  "dash-ag-grid",
  "dash-resizeable-panels",
  "dash-tvlwc",
  "dashvis",
  "flask-caching",
  "fathon",
  "geopandas",
  "glom",
  "hishel",
  "httpx",
  "img2table",
  "lxml",
  "numba",
  "numpy",
  "openturns",
  "ordered-set",
  "orjson",
  "pandas",
  "parsel",
  "pycountry",
  "pydantic",
  "pypika",
  "python-dotenv",
  "rapidfuzz",
  "requests",
  "scikit-learn",
  "scipy",
  "sqlalchemy",
  "statsmodels",
  "tabula-py[jpype]",
  "tqdm",
  "wbgapi"
]

[project.optional-dependencies]
dev = [
  "bandit",
  "datamodel-code-generator",
  "icecream",
  "ipykernel",
  "mypy",
  "pipreqs",
  "ruff",
  "uv"
]